# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2.3'
services:
  web:
    &WEB
    build:
      context: .
    links:
      - postgres
      - redis
    env_file:
      - ./.env

  jobs:
    <<: *WEB
    command: bundle exec script/delayed_job run
    env_file:
      - ./.env

  # postgres:
  #   build: ./docker-compose/postgres
  #   environment:
  #     POSTGRES_PASSWORD: sekret

  redis:
    image: redis:alpine
