development:
  bucket_name: <%= ENV.fetch('S3_BUCKET_NAME', 'canvas-assets') %>
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY', 'access_key') %>
  secret_access_key: <%= ENV.fetch('S3_ACCESS_SECRET', 'secret_key') %>
  region: <%= ENV.fetch('S3_REGION', 'us-east-1') %>
  endpoint: <%= ENV.fetch('S3_ENDPOINT', 'https://nyc3.digitaloceanspaces.com') %>

test:
  bucket_name: <%= ENV.fetch('S3_BUCKET_NAME', 'canvas-assets') %>
  access_key_id: <%= ENV.fetch('S3_KEY_ID', 'access_key') %>
  secret_access_key: <%= ENV.fetch('S3_ACCESS_SECRET', 'secret_key') %>
  region: <%= ENV.fetch('S3_REGION', 'us-east-1') %>
  endpoint: <%= ENV.fetch('S3_ENDPOINT', 'https://nyc3.digitaloceanspaces.com') %>


production:
  bucket_name: <%= ENV.fetch('S3_BUCKET_NAME', 'canvas-assets') %>
  access_key_id: <%= ENV.fetch('S3_KEY_ID', 'access_key') %>
  secret_access_key: <%= ENV.fetch('S3_ACCESS_SECRET', 'secret_key') %>
  region: <%= ENV.fetch('S3_REGION', 'us-east-1') %>
  endpoint: <%= ENV.fetch('S3_ENDPOINT', 'https://nyc3.digitaloceanspaces.com') %>

