defaults: &defaults
  host: <%= ENV.fetch('S3_CDN_HOST', 'canvas-canvas-assets.nyc3.digitaloceanspaces.com') %>
  region:  <%= ENV.fetch('S3_REGION', 'us-east-1') %>
  bucket: <%= ENV.fetch('S3_BUCKET_NAME', 'canvas-assets') %>
  aws_access_key_id: <%= ENV.fetch('S3_ACCESS_KEY', 'access_key') %>
  aws_secret_access_key:  <%= ENV.fetch('S3_ACCESS_SECRET', 'secret_key') %>
  server: <%= ENV.fetch('S3_ENDPOINT', 'https://nyc3.digitaloceanspaces.com') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
