production: &production
  address: <%= ENV.fetch('SMTP_ADDRESS', 'localhost') %>
  port: <%= ENV.fetch('SMTP_PORT', '25') %>
#  user_name: <%= ENV.fetch('SMTP_USER_NAME', '') %>
#  password: <%= ENV.fetch('SMTP_PASSWORD', '') %>
#  authentication: <%= ENV.fetch('SMTP_AUTHENTICATION', '') %>
  domain: <%= ENV.fetch('SMTP_DOMAIN', 'canvas.docker') %>
  outgoing_address: <%= ENV.fetch('SMTP_OUTGOING_ADDRESS', 'admin@canvas.docker') %>
  default_name: <%= ENV.fetch('SMTP_DEFAULT_NAME','canvas') %>

development:
  <<: *production
